// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/mm","id":"2"},"3":{"path":"/login","id":"3"},"4":{"path":"/register","id":"4"},"5":{"path":"/password","id":"5"},"6":{"path":"/detect","id":"6"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__home__mm" */'@/pages/home/mm.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__home__mm" */'@/pages/home/mm.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__home__login" */'@/pages/home/login.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__home__register" */'@/pages/home/register.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__home__password" */'@/pages/home/password.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__home__detect" */'@/pages/home/detect.tsx')),
},
  };
}
